#!/bin/bash
cd /sys/kernel/config/usb_gadget/

# --- CLEANUP (Delete old config if it exists) ---
if [ -d "cyberdeck" ]; then
    echo "" > cyberdeck/UDC
    rm -f cyberdeck/configs/c.1/hid.usb0
    rmdir cyberdeck/configs/c.1/strings/0x409
    rmdir cyberdeck/configs/c.1
    rmdir cyberdeck/functions/hid.usb0
    rmdir cyberdeck/strings/0x409
    rmdir cyberdeck
fi

# --- CREATE NEW GADGET ---
mkdir -p cyberdeck
cd cyberdeck
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2

mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "Cyberdeck Industries" > strings/0x409/manufacturer
echo "Payload Module" > strings/0x409/product

mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length

# Keyboard Report Descriptor
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc

mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

# Link the function to the config
ln -s functions/hid.usb0 configs/c.1/

# Activate the gadget
ls /sys/class/udc > UDC
